/* Atlas Exit Explorer. No tracker, external runtime or generated country scores. */
(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normal=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const C=window.ATLAS_CATALOG||{},P=window.ATLAS_PEACE||{},S=window.ATLAS_SOURCES||{},FEATURED=window.ATLAS_FEATURED||[];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const fmt=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(n);
let toastTimer;
function toast(text){const el=$('#toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
const sourceLink=(key,label)=>`<a class="detail-source" href="${esc(S[key]||S.tax)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
function setupIntake(){const f=$('#intakeForm');if(!f)return;const q=new URLSearchParams(location.search);const chosen=(q.get('countries')||q.get('country')||'').split(',').filter(x=>/^[A-Z]{3}$/.test(x)).slice(0,4);const names={CHE:'Suisse',SGP:'Singapour',ARE:'Émirats arabes unis',PRT:'Portugal',THA:'Thaïlande',USA:'États-Unis',AND:'Andorre',MCO:'Monaco',FRA:'France',DEU:'Allemagne',CAN:'Canada',ESP:'Espagne',GBR:'Royaume-Uni',IRL:'Irlande',AUS:'Australie',NZL:'Nouvelle-Zélande',JPN:'Japon',ITA:'Italie'};$('#destinations').value=chosen.map(id=>names[id]||id).join(', ');const select=$('#offer');if(['cadrage','coordination','installation'].includes(q.get('offer')))select.value=q.get('offer');f.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;const data=new FormData(f);const content=`Bonjour,\n\nJe souhaite échanger sur mon projet d’expatriation.\n\nNom : ${data.get('name')}\nEmail : ${data.get('email')}\nDépart : ${data.get('origin')}\nDestinations : ${data.get('destinations')}\nHorizon : ${data.get('horizon')}\nAccompagnement : ${select.selectedOptions[0].text}\n\n${data.get('context')||''}\n\nMerci.`;const subject='Atlas Exit — Mon projet';$('#sendMail').href=`mailto:aria.zarifian1@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(content)}`;$('#sendGmail').href=`https://mail.google.com/mail/?view=cm&fs=1&to=aria.zarifian1%40gmail.com&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(content)}`;$('#ready').hidden=false;$('#ready').focus();$('#copyRequest').onclick=async()=>{try{await navigator.clipboard.writeText(content);$('#copyRequest').textContent='Message copié'}catch{const p=$('#copyFallback');p.hidden=false;p.value=content;p.select()}}});}
if(!$('#worldMap')){setupIntake();return;}
const svg=$('#worldMap'),group=$('#mapTransform'),layerGroup=$('#countries'),labelsGroup=$('#mapLabels'),pinsGroup=$('#pins'),NS='http://www.w3.org/2000/svg';
const regionNames={Europe:'Europe',Asia:'Asie',Africa:'Afrique',Oceania:'Océanie','North America':'Amérique du Nord','South America':'Amérique du Sud','Seven seas (open ocean)':'Îles & territoires'};
let saved=[];try{const a=JSON.parse(localStorage.getItem('atlas-exit-selection-v1')||'[]');if(Array.isArray(a))saved=a.filter(x=>typeof x==='string'&&/^[A-Z]{3}$/.test(x)).slice(0,4)}catch{}
function configureViewport(){svg.setAttribute('preserveAspectRatio',innerWidth<=900?'xMidYMid slice':'xMidYMid meet')}configureViewport();window.addEventListener('resize',configureViewport);
const state={region:'all',layer:'explore',query:'',tax:60,peace:170,onlySaved:false,selected:null,saved,k:1,x:0,y:0};
let countries=[],byId={},pinEls=[],labelEls=[],paths={},animation=0,hoverId=null,clockInterval,ready=false;
function project(lon,lat){const phi=lat*Math.PI/180,lam=lon*Math.PI/180,t=Math.asin(Math.sqrt(3)/2*Math.sin(phi)),t2=t*t,t6=t2*t2*t2;const x=2*Math.sqrt(3)*lam*Math.cos(t)/(3*(1.340264+3*(-.081106)*t2+t6*(7*.000893+9*.003796*t2)));const y=t*(1.340264-.081106*t2+t6*(.000893+.003796*t2));return[800+268*x,462-268*y]}
function decode(s){let pos=0,x=0,y=0,arr=[];function value(){let r=0,shift=0,b;do{if(pos>=s.length)throw Error('Incomplete geometry');b=s.charCodeAt(pos++)-63;r|=(b&31)<<shift;shift+=5;if(shift>30)throw Error('Invalid geometry')}while(b>=32);return r&1?~(r>>1):r>>1}while(pos<s.length){x+=value();y+=value();arr.push([x/10,y/10])}return arr}
function pathFor(rings){return rings.map(r=>r.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join('')+'Z').join('')}
function node(tag,attrs={},parent){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(parent)parent.append(n);return n}
function val(c){if(state.layer==='peace')return c.peace!=null?`#${c.peace}`:'—';if(state.layer==='tax')return c.tax!=null?`${fmt(c.tax)} %`:c.taxLabel||'—';return c.tax!=null?`${fmt(c.tax)} %`:c.peace!=null?`GPI #${c.peace}`:c.taxLabel||'↗'}
function regionMatch(c){return state.region==='all'||c.region===state.region||(state.region==='Americas'&&c.region.includes('America'))}
function matches(c){return regionMatch(c)&&(!state.onlySaved||state.saved.includes(c.id))&&(state.tax===60||(c.tax!=null&&c.tax<=state.tax))&&(state.peace===170||(c.peace!=null&&c.peace<=state.peace))&&(!state.query||normal(c.name+' '+c.code+' '+c.id+' '+(c.city||'')+' '+(c.id==='ARE'?'dubai emirats abu dhabi':'')+' '+(c.id==='USA'?'usa etats unis new york':'')).includes(normal(state.query)))}
function rank(c){if(state.layer==='tax')return c.tax==null?1000:c.tax;if(state.layer==='peace')return c.peace??1000;const i=FEATURED.indexOf(c.id);return i<0?(c.documented?30:100):i}
function filtered(){return countries.filter(matches).sort((a,b)=>rank(a)-rank(b)||a.name.localeCompare(b.name,'fr'))}
function mix(a,b,t){const ca=a.match(/\w\w/g).map(v=>parseInt(v,16)),cb=b.match(/\w\w/g).map(v=>parseInt(v,16));return'#'+ca.map((v,i)=>Math.round(v+(cb[i]-v)*Math.max(0,Math.min(1,t))).toString(16).padStart(2,'0')).join('')}
function colour(c){if(state.layer==='tax')return c.tax==null?'#213034':mix('91ba9f','4e5d70',c.tax/55);if(state.layer==='peace')return c.peace==null?'#213034':mix('96bba2','5f4050',(c.peace-1)/162);return c.documented?'#47776e':({Europe:'#2e484c',Asia:'#30484a',Africa:'#253b41','North America':'#344c51','South America':'#314c50',Oceania:'#355051'}[c.region]||'#213338')}
function updateMap(){for(const c of countries){const p=paths[c.id];if(p){p.style.fill=colour(c);p.classList.toggle('filtered',!matches(c));p.classList.toggle('selected',state.selected===c.id);p.classList.toggle('hovered',hoverId===c.id)}}for(const p of pinEls){const c=byId[p.id];p.el.style.opacity=matches(c)?1:.16;p.el.classList.toggle('selected',state.selected===p.id)}const titles={explore:['VOTRE PROCHAIN CHAPITRE','Tout commence par un endroit.'],tax:['UN ANGLE PARMI D’AUTRES','La fiscalité change la perspective.'],peace:['GLOBAL PEACE INDEX · 2025','Un autre regard sur le monde.']};$('#mapLabel').textContent=titles[state.layer][0];$('#mapSubtitle').textContent=titles[state.layer][1];$('#legend').innerHTML=state.layer==='explore'?'<span class="legend-dot"></span><span>Repères documentés</span><span class="legend-muted"></span><span>À compléter</span>':state.layer==='tax'?'<span class="legend-gradient"></span><span>0 → 55 % · taux supérieurs, périmètres distincts</span><span class="legend-muted"></span><span>Non comparable / absent</span>':'<span class="legend-gradient"></span><span>Rang 1 → 163 · sélection du GPI 2025</span><span class="legend-muted"></span><span>Non renseigné</span>'}
function renderList(){const list=filtered();$('#resultCount').textContent=`${list.length} destination${list.length>1?'s':''}`;$('#surpriseBtn').disabled=!list.length;$('#results').innerHTML=list.length?list.map(c=>`<button class="country-row ${state.selected===c.id?'selected':''}" data-country="${c.id}" aria-label="Explorer ${esc(c.name)}"><span class="country-code">${esc(c.code)}</span><span class="row-copy"><b>${esc(c.name)}</b><small>${esc(regionNames[c.region]||c.region)}${state.saved.includes(c.id)?' · dans ma sélection':''}</small></span><span class="row-value ${c.documented?'':'dim'}">${esc(val(c))}</span><span class="row-arrow">↗</span></button>`).join(''):`<div class="empty"><b>${state.onlySaved?'Votre sélection est encore vide.':'Aucune destination avec ces filtres.'}</b>${state.onlySaved?'Explorez un pays, puis ajoutez-le à votre sélection.':'Les valeurs non documentées ne sont pas considérées comme zéro.'}<button class="button secondary" data-reset>Revenir à l’exploration</button></div>`;$('#taxOutput').textContent=state.tax===60?'Tous':`≤ ${state.tax} %`;$('#peaceOutput').textContent=state.peace===170?'Tous':`Top ${state.peace}`;$('#filterBadge').textContent=(state.region!=='all'?1:0)+(state.tax!==60?1:0)+(state.peace!==170?1:0)||'';$('#savedToggle').classList.toggle('on',state.onlySaved)}
function persist(){try{localStorage.setItem('atlas-exit-selection-v1',JSON.stringify(state.saved))}catch{toast('La sélection est disponible pour cette visite seulement.')}}
function updateSelection(){state.saved=state.saved.filter(id=>byId[id]);$('#savedCount').textContent=state.saved.length;$('#compareTray').hidden=!state.saved.length;$('#trayCountries').innerHTML=state.saved.map(id=>`<div class="tray-country"><small>${esc(byId[id].code)}</small><span>${esc(byId[id].name)}</span><button data-unsave="${id}" aria-label="Retirer ${esc(byId[id].name)}">×</button></div>`).join('');$('#compareCount').textContent=state.saved.length;$('#openCompare').disabled=state.saved.length<2;$('#topStart').href=projectUrl();$('#compareStart').href=projectUrl();}
function projectUrl(ids=state.saved){return`start.html${ids.length?'?countries='+encodeURIComponent(ids.join(',')):''}`}
function toggleSave(id){if(state.saved.includes(id))state.saved=state.saved.filter(x=>x!==id);else{if(state.saved.length===4){toast('Comparez jusqu’à quatre pays. Retirez-en un pour en ajouter un autre.');return}state.saved.push(id);toast('Destination ajoutée à votre sélection.')}persist();updateSelection();renderList();if(state.selected)renderInspector(byId[state.selected]);}
function refresh(){renderList();updateMap();updateSelection();}
function setRegion(region){state.region=region;$$('[data-region]').forEach(b=>{b.classList.toggle('on',b.dataset.region===region);b.setAttribute('aria-pressed',String(b.dataset.region===region))});refresh();const presets={Europe:[14,50,2.8],Asia:[91,28,1.65],Americas:[-88,16,1.45],Africa:[20,3,1.9],Oceania:[139,-25,1.8]};if(presets[region]){const[x,y,k]=presets[region],p=project(x,y);fly(800-p[0]*k,450-p[1]*k,k)}else resetMap();}
function resetFilters(){state.query='';state.region='all';state.tax=60;state.peace=170;state.onlySaved=false;$('#countrySearch').value='';$('#taxRange').value=60;$('#peaceRange').value=170;setRegion('all')}
function hideTip(){hoverId=null;$('#tooltip').hidden=true;updateMap();}
function showTip(c,e){if(!c||e.pointerType==='touch'||innerWidth<=900)return;hoverId=c.id;const el=$('#tooltip');const rate=c.tax!=null?`${fmt(c.tax)} %`:c.taxLabel||'—';el.innerHTML=`<div class="tip-head"><span class="country-code">${esc(c.code)}</span><div><strong>${esc(c.name)}</strong><small>${esc(regionNames[c.region]||c.region)}</small></div></div><div class="tip-metrics"><div><small>${esc(c.scope||'Repère fiscal')}</small><b>${esc(rate)}</b></div><div><small>Paix · GPI 2025</small><b>${c.peace!=null?'#'+c.peace:'—'}</b></div></div><p class="tip-end">${matches(c)?'Cliquer pour explorer ↗':'Hors de vos filtres · explorer ↗'}</p>`;el.hidden=false;const r=$('.map-shell').getBoundingClientRect();let x=e.clientX-r.left+18,y=e.clientY-r.top-28;x=Math.max(8,Math.min(x,r.width-250));y=Math.max(75,Math.min(y,r.height-el.offsetHeight-45));el.style.left=x+'px';el.style.top=y+'px';updateMap();}
function updateClock(){const c=byId[state.selected];const el=$('#localClock');if(el&&c?.zone){try{el.textContent=new Intl.DateTimeFormat('fr-FR',{timeZone:c.zone,hour:'2-digit',minute:'2-digit'}).format(new Date());el.dateTime=new Date().toISOString()}catch{el.textContent='—'}}}
function renderInspector(c){if(!c)return;clearInterval(clockInterval);const isSaved=state.saved.includes(c.id),rate=c.tax!=null?`${fmt(c.tax)} %`:c.taxLabel||'Non renseigné';const bounds=c.bounds||[0,0,100,100],bw=bounds[2]-bounds[0]||50,bh=bounds[3]-bounds[1]||50;const silhouette=c.path?`<svg viewBox="${bounds[0]-bw*.2} ${bounds[1]-bh*.2} ${bw*1.4} ${bh*1.4}" aria-hidden="true"><path d="${c.path}"/></svg>`:'';$('#inspectorContent').innerHTML=`<div class="inspector-visual">${silhouette}<div class="inspector-tools"><button class="icon-button" data-share="${c.id}" aria-label="Copier le lien de cette destination" title="Partager">↗</button><button class="icon-button" data-dismiss aria-label="Fermer la fiche">×</button></div><span class="coordinates">${Math.abs(c.lat).toFixed(2)}° ${c.lat<0?'S':'N'} &nbsp; ${Math.abs(c.lon).toFixed(2)}° ${c.lon<0?'O':'E'}</span></div><div class="inspector-body"><span class="eyebrow">${esc(regionNames[c.region]||c.region)} · EXPLORER</span><div class="inspector-title"><h2>${esc(c.name)}</h2><span class="country-code">${esc(c.code)}</span></div><p class="inspector-sub">${esc(c.tag||'Un nouvel horizon à examiner, à votre rythme.')}</p><div class="metrics-pair"><div><small>Impôt personnel · repère</small><strong class="${rate.length>9?'long':''}">${esc(rate)}</strong><p class="scope">${esc(c.scope||'Pas de taux comparable')}</p></div><div><small>Paix · GPI 2025</small><strong>${c.peace!=null?'#'+c.peace:'—'}</strong><p class="scope">${c.peace!=null?'sur 163 · édition historique':'Non documenté ici'}</p></div></div><section class="detail-section"><h3>LE CHIFFRE NE DIT PAS TOUT</h3><p>${esc(c.note||(c.tax!=null?'Taux supérieur du barème, pas votre taux effectif. Résidence, source du revenu, taxes locales et cotisations restent à examiner.':'Aucun repère fiscal suffisamment documenté dans cette version. Une absence de donnée ne signifie pas une absence d’impôt.'))}</p>${c.tax!=null||c.src?sourceLink(c.src||'tax','Source fiscale · consulter le périmètre'):''}</section>${c.peace!=null?`<section class="detail-section"><h3>COMMENT LIRE CE CLASSEMENT ?</h3><p>Le GPI 2025 mesure paix, conflits et militarisation. Il ne décrit ni la situation actuelle en 2026 ni la sécurité d’un quartier.</p>${sourceLink('peace','IEP · Global Peace Index 2025, pp. 8–9')}</section>`:''}${c.angle?`<section class="detail-section"><h3>À EXPLORER POUR VOTRE PROJET</h3><p>${esc(c.angle)}</p></section>`:''}${c.zone?`<div class="local-time"><span>En ce moment à ${esc(c.city)}</span><time id="localClock">—</time></div>`:''}<button class="button ${isSaved?'secondary':''}" data-save="${c.id}">${isSaved?'✓ Dans ma sélection':'＋ Garder cette destination'}</button><a class="next-link" href="${projectUrl([c.id])}">Et si j’en faisais mon projet ? ↗</a><p class="source-note">Repères consultés le 14.09.2026. Aucun score global. <a href="methodologie.html">Méthode ↗</a></p></div>`;updateClock();clockInterval=setInterval(updateClock,30000);}
function selectCountry(id,move=true){const c=byId[id];if(!c)return;state.selected=id;hideTip();$('#inspector').hidden=false;renderInspector(c);refresh();$('#sidebar').classList.remove('open');$('#mobileFilters').setAttribute('aria-expanded','false');$('#mobileFilters').classList.remove('on');const hash=`country=${encodeURIComponent(id)}&layer=${state.layer}`;try{history.replaceState(null,'','#'+hash)}catch{}if(move){const p=project(c.lon,c.lat);const k=innerWidth<=900?2.3:2.2;fly((innerWidth<=900?800:575)-p[0]*k,(innerWidth<=900?290:425)-p[1]*k,k)}$('#mapHelp').classList.add('hide');}
function dismiss(){state.selected=null;$('#inspector').hidden=true;clearInterval(clockInterval);try{history.replaceState(null,'',location.pathname)}catch{}refresh();}
function renderComparison(){const sel=state.saved.map(id=>byId[id]).filter(Boolean);const row=(label,f)=>`<tr><td>${label}</td>${sel.map(c=>`<td>${f(c)}</td>`).join('')}</tr>`;$('#compareTable').innerHTML=`<table class="comparison-table"><thead><tr><th>${sel.length} horizons<br>sans classement global</th>${sel.map(c=>`<th><span class="eyebrow">${esc(c.code)}</span>${esc(c.name)}</th>`).join('')}</tr></thead><tbody>${row('Impôt personnel',c=>`<span class="val">${c.tax!=null?fmt(c.tax)+' %':esc(c.taxLabel||'—')}</span><small>${esc(c.scope||'À documenter')}</small>`)}${row('Limites du chiffre',c=>`<small>${esc(c.note||'Taux supérieur, non effectif. Hors cotisations et éventuelles taxes additionnelles.')}</small>`)}${row('Paix · GPI 2025',c=>`<span class="val">${c.peace!=null?'#'+c.peace:'—'}</span><small>Édition historique, pas une alerte de voyage.</small>`)}${row('Zone géographique',c=>esc(regionNames[c.region]||c.region))}${row('Vérifier à la source',c=>`${c.tax!=null||c.src?sourceLink(c.src||'tax','Fiscalité'):''}${c.peace!=null?' '+sourceLink('peace','Paix 2025'):''}`)}${row('Votre projet',c=>`<a class="text-link" href="${projectUrl([c.id])}">Explorer la suite ↗</a>`)}</tbody></table>`;$('#compareStart').href=projectUrl();$('#compareDialog').showModal();}
function transform(){group.setAttribute('transform',`translate(${state.x} ${state.y}) scale(${state.k})`);pinEls.forEach(p=>p.el.setAttribute('transform',`translate(${p.x} ${p.y}) scale(${1/state.k})`));labelEls.forEach(p=>{p.el.setAttribute('transform',`translate(${p.x} ${p.y}) scale(${1/Math.sqrt(state.k)})`);p.el.style.opacity=state.k>3?.15:.42});$('#zoomValue').textContent=fmt(state.k)+'×'}
function fly(x,y,k,duration=650){cancelAnimationFrame(animation);const begin=performance.now(),from={x:state.x,y:state.y,k:state.k};const dur=reduced?0:duration;function tick(t){const u=dur?Math.min(1,(t-begin)/dur):1,v=1-Math.pow(1-u,3);state.x=from.x+(x-from.x)*v;state.y=from.y+(y-from.y)*v;state.k=from.k+(k-from.k)*v;transform();if(u<1)animation=requestAnimationFrame(tick)}animation=requestAnimationFrame(tick)}
function resetMap(){const r=svg.getBoundingClientRect(),k=innerWidth<=900?Math.min(1,r.width/(r.height*1600/900)*.97):1;fly(800*(1-k),450*(1-k),k);$('#coords').textContent='ATLAS / WORLD EXPLORER'}
function point(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:800,y:450}}
function zoom(f,p={x:800,y:450},smooth=true){const k=Math.min(9,Math.max(innerWidth<=900?.22:.6,state.k*f)),r=k/state.k,x=p.x-(p.x-state.x)*r,y=p.y-(p.y-state.y)*r;if(smooth)fly(x,y,k,250);else{state.k=k;state.x=x;state.y=y;transform()}$('#mapHelp').classList.add('hide');hideTip()}
const pointers=new Map();let lastPoint,downId,downScreen,moved=false,pinch,velocity={x:0,y:0},lastTime=0;
svg.addEventListener('pointerdown',e=>{if(e.button&&e.button!==0)return;cancelAnimationFrame(animation);pointers.set(e.pointerId,point(e));svg.setPointerCapture(e.pointerId);lastPoint=point(e);downScreen={x:e.clientX,y:e.clientY};downId=e.target.closest('[data-id]')?.dataset.id;moved=false;lastTime=performance.now();velocity={x:0,y:0};if(pointers.size===2){const a=[...pointers.values()];pinch={distance:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),k:state.k};moved=true}svg.classList.add('dragging');hideTip()});
svg.addEventListener('pointermove',e=>{const p=point(e);if(pointers.has(e.pointerId)){pointers.set(e.pointerId,p);if(Math.hypot(e.clientX-downScreen.x,e.clientY-downScreen.y)>5)moved=true;$('#mapHelp').classList.add('hide');if(pointers.size===2){const a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),mid={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2};if(pinch&&dist)zoom((pinch.k*dist/pinch.distance)/state.k,mid,false);moved=true}else if(lastPoint){const now=performance.now(),dt=Math.max(8,now-lastTime),dx=p.x-lastPoint.x,dy=p.y-lastPoint.y;state.x+=dx;state.y+=dy;velocity={x:dx/dt,y:dy/dt};lastTime=now;transform()}lastPoint=p;return}const id=e.target.closest('[data-id]')?.dataset.id;if(id)showTip(byId[id],e);else if(hoverId)hideTip();});
function endPointer(e){const hadPinch=!!pinch;pointers.delete(e.pointerId);if(pointers.size){pinch=null;lastPoint=[...pointers.values()][0];moved=true;return}svg.classList.remove('dragging');if(!moved&&!hadPinch&&downId&&e.type!=='pointercancel')selectCountry(downId);else if(moved&&!hadPinch&&!reduced&&Math.hypot(velocity.x,velocity.y)>.12){fly(state.x+velocity.x*95,state.y+velocity.y*95,state.k,400)}pinch=null;lastPoint=null;downId=null}
svg.addEventListener('pointerup',endPointer);svg.addEventListener('pointercancel',endPointer);svg.addEventListener('pointerleave',()=>{if(!pointers.size)hideTip()});
svg.addEventListener('wheel',e=>{e.preventDefault();cancelAnimationFrame(animation);zoom(Math.exp(-e.deltaY*.0017),point(e),false)},{passive:false});svg.addEventListener('dblclick',e=>{e.preventDefault();zoom(1.6,point(e))});
svg.addEventListener('keydown',e=>{const steps={ArrowLeft:[80,0],ArrowRight:[-80,0],ArrowUp:[0,80],ArrowDown:[0,-80]};if(steps[e.key]){e.preventDefault();fly(state.x+steps[e.key][0],state.y+steps[e.key][1],state.k,180)}else if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1.4)}else if(e.key==='-'){e.preventDefault();zoom(1/1.4)}else if(e.key==='0'){e.preventDefault();resetMap()}});
function graticule(){const g=$('#graticule');for(let lon=-180;lon<=180;lon+=30){const pts=[];for(let lat=-80;lat<=85;lat+=3)pts.push(project(lon,lat));node('path',{d:pts.map((p,i)=>(i?'L':'M')+p.join(',')).join(''),class:'graticule'},g)}for(let lat=-60;lat<=60;lat+=30){const pts=[];for(let lon=-180;lon<=180;lon+=3)pts.push(project(lon,lat));node('path',{d:pts.map((p,i)=>(i?'L':'M')+p.join(',')).join(''),class:'graticule'+(lat===0?' equator':'')},g)}const tags=[['OCÉAN PACIFIQUE',-144,8,'ocean-label'],['OCÉAN ATLANTIQUE',-34,9,'ocean-label'],['OCÉAN INDIEN',73,-25,'ocean-label'],['EUROPE',15,67,'region-label'],['ASIE',96,56,'region-label'],['AFRIQUE',19,4,'region-label']];for(const[t,lon,lat,cl]of tags){const[x,y]=project(lon,lat),el=node('text',{'text-anchor':'middle',class:cl},labelsGroup);el.textContent=t;labelEls.push({el,x,y})}}
function fromGeo(r){const[id,code,name,region,lon,lat,encoded]=r,meta=C[id]||{};const rings=encoded.map(decode).map(ring=>ring.map(p=>project(...p)));const flat=rings.flat();let bounds=[Math.min(...flat.map(p=>p[0])),Math.min(...flat.map(p=>p[1])),Math.max(...flat.map(p=>p[0])),Math.max(...flat.map(p=>p[1]))];return{id,code,name,region,lon,lat,...meta,lon:meta.pin?.[0]??lon,lat:meta.pin?.[1]??lat,peace:P[id]??null,tax:null,...meta,path:pathFor(rings),bounds,documented:!!C[id]||P[id]!=null}}
async function load(){try{const r=await fetch('geography.json?v=map3');if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(!Array.isArray(data)||data.length<150)throw Error('Invalid geography');countries=data.map(fromGeo);for(const[id,code,name,region]of[['AND','AD','Andorre','Europe'],['MCO','MC','Monaco','Europe'],['SGP','SG','Singapour','Asia']]){if(!countries.some(c=>c.id===id)){const m=C[id];countries.push({id,code,name,region,lon:m.pin[0],lat:m.pin[1],...m,peace:P[id]??null,documented:true,path:''})}}byId=Object.fromEntries(countries.map(c=>[c.id,c]));graticule();for(const c of countries){if(c.path){const el=node('path',{d:c.path,'data-id':c.id,class:'country-shape'},layerGroup);const t=node('title',{},el);t.textContent=c.name;paths[c.id]=el}if(FEATURED.includes(c.id)||c.id==='MCO'){const[x,y]=project(c.lon,c.lat),el=node('g',{'data-id':c.id,class:'country-pin'},pinsGroup);node('circle',{class:'halo',r:11},el);node('circle',{class:'core',r:3.8},el);const t=node('text',{class:'pin-label',x:9,y:4},el);t.textContent=c.name;pinEls.push({id:c.id,el,x,y})}}$('#mapError').hidden=true;ready=true;refresh();transform();const q=new URLSearchParams(location.hash.slice(1));if(['tax','peace','explore'].includes(q.get('layer')))setLayer(q.get('layer'));if(byId[q.get('country')])selectCountry(q.get('country'));}catch(err){console.error('Atlas map:',err);$('#mapError').hidden=false;$('#resultCount').textContent='Chargement indisponible';$('#results').innerHTML='<div class="empty">La carte est momentanément indisponible. Rechargez la page ou consultez les sources.</div>'}}
function setLayer(layer){state.layer=layer;$$('[data-layer]').forEach(b=>{b.classList.toggle('on',b.dataset.layer===layer);b.setAttribute('aria-pressed',String(b.dataset.layer===layer))});refresh();hideTip()}
$('#countrySearch').addEventListener('input',e=>{state.query=e.target.value;refresh()});$('#countrySearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const first=filtered()[0];if(first)selectCountry(first.id)}});$('#taxRange').addEventListener('input',e=>{state.tax=Number(e.target.value);if(state.layer!=='tax')setLayer('tax');else refresh()});$('#peaceRange').addEventListener('input',e=>{state.peace=Number(e.target.value);if(state.layer!=='peace')setLayer('peace');else refresh()});$('#resetFilters').onclick=resetFilters;$$('[data-region]').forEach(b=>b.onclick=()=>setRegion(b.dataset.region));$$('[data-layer]').forEach(b=>b.onclick=()=>setLayer(b.dataset.layer));$('#zoomIn').onclick=()=>zoom(1.4);$('#zoomOut').onclick=()=>zoom(1/1.4);$('#homeMap').onclick=()=>{dismiss();resetMap()};$('#focusMode').onclick=()=>{document.body.classList.toggle('immersive');$('#focusMode').setAttribute('aria-label',document.body.classList.contains('immersive')?'Afficher les filtres':'Masquer le panneau pour agrandir la carte')};$('#mobileFilters').onclick=()=>{const on=$('#sidebar').classList.toggle('open');$('#mobileFilters').classList.toggle('on',on);$('#mobileFilters').setAttribute('aria-expanded',String(on));if(on)dismiss()};$('#savedToggle').onclick=()=>{state.onlySaved=!state.onlySaved;refresh();if(innerWidth<=900){$('#sidebar').classList.add('open');$('#mobileFilters').classList.add('on');$('#mobileFilters').setAttribute('aria-expanded','true')}};$('#surpriseBtn').onclick=()=>{const all=filtered(),list=all.filter(c=>c.documented&&c.id!==state.selected),pool=list.length?list:all;if(pool.length)selectCountry(pool[Math.floor(Math.random()*pool.length)].id)};$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#openCompare').onclick=()=>{if(state.saved.length>=2)renderComparison()};$('#reloadMap').onclick=()=>location.reload();$$('[data-method]').forEach(b=>b.onclick=()=>location.href='methodologie.html');
document.addEventListener('click',async e=>{const target=e.target.closest('button,a');if(!target)return;if(target.dataset.country)selectCountry(target.dataset.country);if(target.dataset.save)toggleSave(target.dataset.save);if(target.dataset.unsave)toggleSave(target.dataset.unsave);if('dismiss'in target.dataset)dismiss();if('reset'in target.dataset)resetFilters();if('close'in target.dataset)target.closest('dialog')?.close();if(target.dataset.share){const url=location.origin+location.pathname+'#country='+target.dataset.share+'&layer='+state.layer;try{await navigator.clipboard.writeText(url);toast('Lien de la destination copié.')}catch{toast('Le lien de ce pays est dans la barre d’adresse.')}}});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){hideTip();if(!$('dialog[open]'))dismiss();$('#sidebar').classList.remove('open');$('#mobileFilters').setAttribute('aria-expanded','false');$('#mobileFilters').classList.remove('on')}if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();if(innerWidth<=900)$('#sidebar').classList.add('open');$('#countrySearch').focus()}});window.addEventListener('hashchange',()=>{const q=new URLSearchParams(location.hash.slice(1));if(byId[q.get('country')])selectCountry(q.get('country'))});load();
window.AtlasExplorer={state,project,getCountries:()=>countries,selectCountry,resetFilters,ready:()=>ready};
})();
