if(!root.document)return;const document=root.document;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=value=>{const [y,m,d]=String(value).split('-');return y&&m&&d?`${d}.${m}.${y}`:value;};
const stateLabel=state=>state==='READY_WITH_CAVEAT'?'Vérifié · limites':state==='READY_FOR_PRODUCT'?'Vérifié':'À revalider';
const activeCountryId=container=>container?.querySelector('[data-save]')?.getAttribute('data-save')||null;
function rowMarkup(key,r){const display=core.safeDisplay(r);return `<article class="atlas-evidence__row" data-evidence-field="${esc(key)}" data-evidence-state="${esc(r.state)}"><div class="atlas-evidence__row-head"><span>${esc(core.fieldLabels[key]||key)}</span><small>${esc(stateLabel(r.state))}</small></div><strong>${esc(display.headline)}</strong><p>${esc(display.summary)}</p><details class="atlas-evidence__source"><summary>Source & limites</summary><p class="micro">${esc(r.jurisdiction)} · vérifié ${esc(dateLabel(r.verifiedOn))} · ${esc(r.freshness.cadence)}</p><p class="micro">${esc(r.caveat)}</p>${core.renderSources(r)}</details></article>`;}
function panelMarkup(){const fiscal=['tax_residency','pit','cit_business','consumption_tax'],practical=['cost_context','residence_visa','healthcare','safety_context'];return `<details class="context-disclosure atlas-evidence" data-atlas-singapore-evidence data-country="SGP" open><summary>Repères sourcés · vie, statut & fiscalité</summary><section class="detail-section atlas-evidence__section"><div class="atlas-evidence__intro"><span class="eyebrow">EVIDENCE LAYER · ${esc(SGP.schemaVersion)}</span><p>8 repères officiels DEX-18, 10 sources directes et 2 ensembles multi-sources. Résidence fiscale, work pass, santé, coût et sécurité restent conditionnels ; aucun score ou taux total synthétique.</p></div><div class="atlas-evidence__group"><h3>Fiscalité</h3>${fiscal.map(k=>rowMarkup(k,SGP.fields[k])).join('')}</div><div class="atlas-evidence__group"><h3>Vie & statut</h3>${practical.map(k=>rowMarkup(k,SGP.fields[k])).join('')}</div></section></details>`;}
function reconcileInspector(container){const legacyTax=container.querySelector('.tax-stack');if(legacyTax){legacyTax.hidden=true;legacyTax.dataset.atlasLegacyReconciled='SGP';}const legacyDisclosure=container.querySelector('.source-disclosure');if(legacyDisclosure){legacyDisclosure.hidden=true;legacyDisclosure.dataset.atlasLegacyReconciled='SGP';}for(const section of container.querySelectorAll('.detail-section')){const heading=section.querySelector('h3')?.textContent?.trim();if(heading==='INSTALLATION · PREMIER REPÈRE'){section.hidden=true;section.dataset.atlasLegacyReconciled='SGP';}}}
function enhanceInspector(){const container=document.querySelector('#inspectorContent');if(!container)return;const id=activeCountryId(container),existing=container.querySelector('[data-atlas-singapore-evidence]');if(id!=='SGP'){if(existing)existing.remove();return;}reconcileInspector(container);if(existing)return;const anchor=container.querySelector('.capital-card')||container.querySelector('.tax-stack');if(!anchor)return;const holder=document.createElement('div');holder.innerHTML=panelMarkup();anchor.insertAdjacentElement('afterend',holder.firstElementChild);}
function mount(){const inspector=document.querySelector('#inspectorContent');if(inspector){enhanceInspector();new MutationObserver(()=>queueMicrotask(enhanceInspector)).observe(inspector,{childList:true,subtree:true});}document.addEventListener('click',()=>setTimeout(enhanceInspector,0));window.addEventListener('hashchange',()=>setTimeout(enhanceInspector,0));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(typeof window!=='undefined'?window:(typeof globalThis!=='undefined'?globalThis:null));
