#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {validateManifest,normalizeRecords}=require('./atlas_country_factory_lib.cjs');

const input=process.argv[2],output=process.argv[3];
if(!input||!output){console.error('usage: node scripts/atlas_country_factory_generate.cjs <manifest.json> <atlas-exit/country-factory-batch-*.js>');process.exit(64);}
const manifest=JSON.parse(fs.readFileSync(input,'utf8'));
const report=validateManifest(manifest,{requireChecksum:true});
if(!report.ok){console.error(JSON.stringify(report,null,2));process.exit(1);}
const cleanSet=new Set(report.clean);
const records=normalizeRecords(manifest).filter(r=>cleanSet.has(String(r.iso3||r.key||'').toUpperCase())).map(r=>JSON.parse(JSON.stringify(r)));
if(records.length<5||records.length>10){console.error(`release batch must contain 5-10 CLEAN records; got ${records.length}`);process.exit(1);}
const payload={
  schemaVersion:'atlas-country-factory-runtime-v1',
  manifestVersion:manifest.manifestVersion,
  manifestChecksum:manifest.checksum,
  checkedOn:manifest.checkedOn,
  clean:report.clean,
  held:report.held,
  records
};
const js=`/* Generated by scripts/atlas_country_factory_generate.cjs. Do not hand-edit. */\n(function(root){'use strict';root.ATLAS_COUNTRY_FACTORY_BATCH=Object.freeze(${JSON.stringify(payload,null,2)});})(typeof window!=='undefined'?window:globalThis);\n`;
fs.mkdirSync(path.dirname(output),{recursive:true});
fs.writeFileSync(output,js);
console.log(JSON.stringify({output,manifestVersion:manifest.manifestVersion,checksum:manifest.checksum,clean:report.clean,held:report.held,records:records.length},null,2));
