const assert=require('node:assert/strict'),fs=require('node:fs');
const{chromium}=require('playwright');
const PRODUCT=process.env.GITHUB_SHA||process.env.ATLAS_PRODUCT_SHA||'UNKNOWN';
const BASE='http://127.0.0.1:8000/atlas-exit/index.html';
const CLEAN=['NLD','SWE','NZL','ITA','HRV'];
const NAMES={NLD:'Pays-Bas',SWE:'Suède',NZL:'Nouvelle-Zélande',ITA:'Italie',HRV:'Croatie'};
const CORE8=['tax_residency','pit','cit_business','consumption_tax','cost_context','residence_visa','healthcare','safety_context'];
const PREVIOUS=['AUT','DNK','FIN','IRL','NOR','BEL','CZE','GRC','LUX','POL'];
const CHECKSUM='a8c84bbabb33e1e2c7c3da78b54843d3e551f9b65ec7ba81d13b0db0af9117b5';
const report={productSha:PRODUCT,manifest:'DEX-CF3-B3',viewports:[],errors:[]};
const sameOrigin=u=>new globalThis.URL(u).origin===new globalThis.URL(BASE).origin;
async function choose(page,name,id,selector){await page.locator('#countrySearch').fill(name);await page.waitForTimeout(180);const row=page.locator(`[data-country="${id}"]`).first();await row.waitFor({state:'attached',timeout:10000});await row.evaluate(el=>el.click());await page.waitForSelector(selector,{timeout:10000});return page.locator(selector);}
async function noOverflow(page){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'page overflow');assert.equal(await page.locator('#inspector').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true,'Inspector overflow');}
async function openEvidence(panel,{requireClosed=false}={}){assert.equal(await panel.locator('[data-evidence-field]').count(),8,'CORE8 field count');const summary=panel.locator(':scope > summary');assert.equal(await summary.count(),1,'outer disclosure summary missing');if(requireClosed)assert.equal(await panel.getAttribute('open'),null,'fresh country evidence should be concise by default');if((await panel.getAttribute('open'))===null)await summary.click();assert.notEqual(await panel.getAttribute('open'),null,'outer disclosure failed to open');const groups=panel.locator('.atlas-evidence__source');assert.equal(await groups.count(),8,'source disclosure count');assert.ok((await groups.evaluateAll(es=>es.map(e=>e.hasAttribute('open')))).every(v=>v===false),'source groups should start closed');const first=groups.first();await first.locator('summary').click();assert.ok(await first.locator('a.detail-source').count()>=1,'source locator missing');assert.equal(await first.locator('a.detail-source').first().isVisible(),true,'source locator not visible after disclosure');}
async function shell(page){for(const s of ['#countrySearch','#inspector','#openCompare','#resetFilters','#zoomIn','#zoomOut','[data-layer="tax"]','[data-layer="stability"]','[data-layer="conflict"]'])assert.equal(await page.locator(s).count(),1,`missing semantic control ${s}`);assert.equal(await page.getByText('Découvrir',{exact:true}).count(),0,'Découvrir must stay removed');assert.equal(await page.getByText('Stabilité politique',{exact:true}).count()>0,true,'Stabilité politique control missing');assert.equal(await page.getByText('Conflit & tensions',{exact:true}).count()>0,true,'Conflit & tensions control missing');}
async function adjacent(ctx){for(const[path,checks]of[['offres.html',['free-guide/usa','guide_download_click','free_funnel_cta','parcours-usa.html']],['parcours-usa.html',['atlas-events.js','USCIS','Roadmap']],['accompagnement.html',['free_funnel_cta','parcours-usa.html','offres.html?countries=USA']]]){const p=await ctx.newPage(),local=[];p.on('pageerror',e=>local.push(String(e)));p.on('requestfailed',r=>{if(sameOrigin(r.url()))local.push('requestfailed:'+r.url())});await p.goto(new globalThis.URL(path,BASE).href,{waitUntil:'domcontentloaded'});const html=await p.locator('html').innerHTML();for(const c of checks)assert.ok(html.includes(c),`${path} missing ${c}`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`${path} overflow`);assert.deepEqual(local,[],`${path} same-origin/page errors`);await p.close();}const eventJs=await(await ctx.request.get(new globalThis.URL('atlas-events.js',BASE).href)).text();assert.match(eventJs,/qualified_project/,'qualified_project event missing');const roadmapJs=await(await ctx.request.get(new globalThis.URL('parcours-usa.js',BASE).href)).text();assert.match(roadmapJs,/QEP_DEDUPE_KEY/,'QEP dedupe marker missing');const sitemap=await(await ctx.request.get(new globalThis.URL('sitemap.xml',BASE).href)).text();assert.match(sitemap,/https:\/\/atlas-expat\.fr\/parcours-usa\.html/,'D1R-17 roadmap sitemap entry missing');}
async function verifyFactory(page){const state=await page.evaluate(({clean,core8})=>{const f=window.ATLAS_COUNTRY_FACTORY,e=window.ATLAS_COUNTRY_EVIDENCE;return{factory:f&&{runtimeVersion:f.runtimeVersion,batchChecksums:f.batchChecksums,batches:f.batches?.map(b=>({manifestId:b.manifestId,registered:[...b.registered],held:[...b.held]})),registered:[...f.registered],held:[...f.held],orphanRecords:[...f.orphanRecords],recordCount:f.recordCount},records:Object.fromEntries(clean.map(id=>[id,{exists:!!e?.countries?.[id],states:core8.map(k=>e?.countries?.[id]?.fields?.[k]?.state),sourceCounts:core8.map(k=>(e?.countries?.[id]?.fields?.[k]?.sources||[]).length),urls:core8.flatMap(k=>(e?.countries?.[id]?.fields?.[k]?.sources||[]).map(s=>s.locator)),ids:core8.flatMap(k=>(e?.countries?.[id]?.fields?.[k]?.evidenceIds||[])),checked:core8.map(k=>e?.countries?.[id]?.fields?.[k]?.checkedOn),refresh:e?.countries?.[id]?.fields?.safety_context?.flags?.release_refresh_required}]))};},{clean:CLEAN,core8:CORE8});assert.ok(state.factory,'Country Factory runtime missing');assert.equal(state.factory.runtimeVersion,'atlas-country-factory-runtime-v3');assert.equal(state.factory.batchChecksums['DEX-CF3-B3'],CHECKSUM,'B3 manifest checksum');assert.equal(state.factory.recordCount,15,'Factory total record count');assert.deepEqual([...state.factory.registered].sort(),[...PREVIOUS,...CLEAN].sort(),'registered factory set');assert.deepEqual(state.factory.held,['ARE'],'held set');assert.deepEqual(state.factory.orphanRecords,[],'Factory records must all exist in Explorer');const b3=state.factory.batches.find(b=>b.manifestId==='DEX-CF3-B3');assert.ok(b3,'B3 batch state missing');assert.deepEqual([...b3.registered].sort(),[...CLEAN].sort(),'B3 registered set');assert.deepEqual(b3.held,['ARE']);for(const id of CLEAN){const r=state.records[id];assert.equal(r.exists,true,`${id} record missing`);assert.equal(r.states.length,8,`${id} CORE8 count`);assert.ok(r.states.every(s=>s==='READY_FOR_PRODUCT'),`${id} non-ready field`);assert.ok(r.urls.length>=8,`${id} locator count`);assert.ok(r.urls.every(u=>/^https:\/\//.test(u)),`${id} non-direct locator`);assert.ok(r.ids.length>=8,`${id} evidence IDs`);assert.ok(r.checked.every(x=>x==='2026-09-24'),`${id} checkedOn`);assert.equal(r.refresh,true,`${id} safety release refresh`);}}
(async()=>{const browser=await chromium.launch({headless:true});for(const vp of[{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844}]){const ctx=await browser.newContext({viewport:{width:vp.width,height:vp.height}}),page=await ctx.newPage(),errs=[];page.on('pageerror',e=>errs.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&!/umami|ERR_FAILED|Failed to load resource/i.test(m.text()))errs.push('console:'+m.text())});page.on('requestfailed',r=>{if(sameOrigin(r.url()))errs.push('requestfailed:'+r.url())});page.on('response',r=>{if(sameOrigin(r.url())&&r.status()>=400)errs.push('http'+r.status()+':'+r.url())});await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.AtlasExplorer?.ready?.()&&window.ATLAS_COUNTRY_FACTORY?.recordCount===15,null,{timeout:15000});await shell(page);await verifyFactory(page);await noOverflow(page);if(vp.name==='mobile'){await page.locator('#mobileFilters').click();assert.equal(await page.locator('#mobileFilters').getAttribute('aria-expanded'),'true','mobile filters failed');}
for(const id of CLEAN){const panel=await choose(page,NAMES[id],id,`[data-atlas-country-factory-evidence][data-country="${id}"]`);assert.equal(await panel.locator('[data-evidence-field]').count(),8,`${id} evidence count`);assert.ok(await panel.locator('a.detail-source').count()>=8,`${id} rendered locators`);assert.ok((await panel.locator('a.detail-source').evaluateAll(as=>as.map(a=>a.href))).every(u=>u.startsWith('https://')),`${id} rendered direct locators`);await openEvidence(panel,{requireClosed:true});await noOverflow(page);}
for(const [name,id,selector] of [['Canada','CAN','[data-atlas-canada-evidence][data-country="CAN"]'],['Portugal','PRT','[data-atlas-portugal-evidence][data-country="PRT"]'],['Allemagne','DEU','[data-atlas-germany-evidence][data-country="DEU"]'],['Royaume-Uni','GBR','[data-atlas-united-kingdom-evidence][data-country="GBR"]']]){const panel=await choose(page,name,id,selector);assert.equal(await panel.locator('[data-evidence-field]').count(),8,`${id} regression evidence`);await noOverflow(page);}
const ita=await page.evaluate(()=>window.ATLAS_COUNTRY_EVIDENCE?.countries?.ITA?.fields);assert.match(ita?.pit?.headline||'',/33\s*%/,'Italy 2026 middle PIT band');assert.doesNotMatch(ita?.pit?.headline||'',/35\s*%/,'Italy stale PIT must not leak');assert.match(ita?.cit_business?.headline||'',/3[,.]50\s*%/,'Italy statutory IRAP base');assert.match(ita?.cit_business?.summary||'',/24\s*%/,'Italy IRES baseline');
await choose(page,'Italie','ITA','[data-atlas-country-factory-evidence][data-country="ITA"]');await page.locator('[data-save="ITA"]').click();await choose(page,'Nouvelle-Zélande','NZL','[data-atlas-country-factory-evidence][data-country="NZL"]');await page.locator('[data-save="NZL"]').click();assert.equal(await page.locator('#savedCount').textContent(),'2','save count');await page.locator('#openCompare').evaluate(el=>el.click());await page.locator('#compareDialog').waitFor({state:'visible',timeout:10000});assert.ok(await page.locator('#compareTable [data-atlas-normalized="ITA"]').count()>=4,'ITA comparator normalization');assert.ok(await page.locator('#compareTable [data-atlas-normalized="NZL"]').count()>=4,'NZL comparator normalization');await page.locator('#compareDialog [data-close]').evaluate(el=>el.click());
await page.locator('[data-layer="conflict"]').evaluate(el=>el.click());await page.waitForFunction(()=>document.querySelector('[data-layer="conflict"]')?.getAttribute('aria-pressed')==='true');await choose(page,'Japon','JPN','[data-conflict-panel]');let t=await page.locator('[data-conflict-panel]').innerText();assert.match(t,/590\s*km/i,'Japan conflict freshness');assert.match(t,/70\s*km/i,'Japan conflict freshness');await choose(page,'Thaïlande','THA','[data-conflict-panel]');t=await page.locator('[data-conflict-panel]').innerText();assert.match(t,/Cambodge|Pattani/i,'Thailand bounded conflict geography');
await page.locator('[data-layer="tax"]').evaluate(el=>el.click());await page.locator('#countrySearch').fill('Pays-Bas');await page.waitForTimeout(150);assert.equal(await page.locator('[data-country="NLD"]').count(),1,'search');await page.locator('#countrySearch').fill('');await page.locator('[data-region="Europe"]').evaluate(el=>el.click());await page.waitForTimeout(120);assert.ok(Number((await page.locator('#resultCount').textContent()).match(/\d+/)?.[0]||0)>0,'filter');await page.locator('#resetFilters').evaluate(el=>el.click());const z0=await page.locator('#zoomValue').textContent();await page.locator('#zoomOut').evaluate(el=>el.click());await page.waitForTimeout(350);const z1=await page.locator('#zoomValue').textContent();assert.notEqual(z1,z0,'zoom out');await page.locator('#zoomIn').evaluate(el=>el.click());await page.waitForTimeout(350);assert.notEqual(await page.locator('#zoomValue').textContent(),z1,'zoom in');await noOverflow(page);await adjacent(ctx);assert.deepEqual(errs,[],'Product console/network/page errors');fs.mkdirSync('qa-artifacts',{recursive:true});await page.screenshot({path:`qa-artifacts/pex-cf3-b3-${vp.name}.png`,fullPage:true});report.viewports.push({...vp,factoryCountries:[...CLEAN],regressions:['CAN','PRT','DEU','GBR'],conflict:['JPN','THA'],interactions:true});report.errors.push(...errs.map(e=>vp.name+':'+e));await ctx.close();}await browser.close();fs.mkdirSync('qa-artifacts',{recursive:true});fs.writeFileSync('qa-artifacts/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exit(1)});
