const assert=require('node:assert/strict'),fs=require('node:fs');
const{chromium}=require('playwright');
const PRODUCT=process.env.GITHUB_SHA||process.env.ATLAS_PRODUCT_SHA||'UNKNOWN';
const BASE='http://127.0.0.1:8000/atlas-exit/index.html';
const CLEAN=['CYP','MLT','GEO','ISL','HUN'];
const NAMES={CYP:'Chypre',MLT:'Malte',GEO:'Géorgie',ISL:'Islande',HUN:'Hongrie'};
const CORE8=['tax_residency','pit','cit_business','consumption_tax','cost_context','residence_visa','healthcare','safety_context'];
const PREVIOUS=['AUT','DNK','FIN','IRL','NOR','BEL','CZE','GRC','LUX','POL','NLD','SWE','NZL','ITA','HRV','EST','LVA','SVK','SVN','BGR'];
const CHECKSUM='dc379438eeaf8d2a9a79639e3e5172ffeedc8e3bf3923216f1a2232de725d31a';
const report={productSha:PRODUCT,manifest:'DEX-CF5-B5',representatives:{normal:'CYP',longest:'HUN',conditional:'GEO',density:'MLT'},viewports:[],errors:[]};
const sameOrigin=u=>new URL(u).origin===new URL(BASE).origin;
async function choose(page,name,id,selector){await page.locator('#countrySearch').fill(name);await page.waitForTimeout(180);const row=page.locator(`[data-country="${id}"]`).first();await row.waitFor({state:'attached',timeout:10000});await row.evaluate(el=>el.click());await page.waitForSelector(selector,{timeout:10000});return page.locator(selector);}
async function noOverflow(page){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'page overflow');assert.equal(await page.locator('#inspector').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true,'Inspector overflow');}
async function disclosure(panel){assert.equal(await panel.locator('[data-evidence-field]').count(),8,'CORE8 count');assert.equal(await panel.getAttribute('open'),null,'concise default disclosure');await panel.locator(':scope > summary').click();assert.notEqual(await panel.getAttribute('open'),null,'outer disclosure failed');const src=panel.locator('.atlas-evidence__source');assert.equal(await src.count(),8,'source disclosure count');assert.ok((await src.evaluateAll(es=>es.map(e=>e.hasAttribute('open')))).every(v=>v===false),'source details start closed');await src.first().locator('summary').click();const a=src.first().locator('a.detail-source').first();assert.ok(await a.count()===1&&await a.isVisible(),'direct source link inaccessible');assert.match(await a.getAttribute('href'),/^https:\/\//);}
async function shell(page){for(const s of ['#countrySearch','#inspector','#openCompare','#resetFilters','#zoomIn','#zoomOut','[data-layer="tax"]','[data-layer="stability"]','[data-layer="conflict"]'])assert.equal(await page.locator(s).count(),1,`missing ${s}`);assert.equal(await page.getByText('Découvrir',{exact:true}).count(),0,'Découvrir reintroduced');assert.ok(await page.getByText('Stabilité politique',{exact:true}).count()>0);assert.ok(await page.getByText('Conflit & tensions',{exact:true}).count()>0);}
async function adjacent(ctx){for(const[path,checks]of[['offres.html',['free-guide/usa','guide_download_click','free_funnel_cta','parcours-usa.html']],['parcours-usa.html',['atlas-events.js','USCIS','Roadmap']],['accompagnement.html',['free_funnel_cta','parcours-usa.html','offres.html?countries=USA']]]){const p=await ctx.newPage(),errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('requestfailed',r=>{if(sameOrigin(r.url()))errs.push('requestfailed:'+r.url())});await p.goto(new URL(path,BASE).href,{waitUntil:'domcontentloaded'});const html=await p.locator('html').innerHTML();for(const c of checks)assert.ok(html.includes(c),`${path} missing ${c}`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`${path} overflow`);assert.deepEqual(errs,[],`${path} errors`);await p.close();}const ev=await(await ctx.request.get(new URL('atlas-events.js',BASE).href)).text();assert.match(ev,/qualified_project/);const rm=await(await ctx.request.get(new URL('parcours-usa.js',BASE).href)).text();assert.match(rm,/QEP_DEDUPE_KEY/);const sitemap=await(await ctx.request.get(new URL('sitemap.xml',BASE).href)).text();assert.match(sitemap,/https:\/\/atlas-expat\.fr\/parcours-usa\.html/);}
async function verifyFactory(page){const state=await page.evaluate(({clean,core8})=>{const f=window.ATLAS_COUNTRY_FACTORY,e=window.ATLAS_COUNTRY_EVIDENCE;return{factory:f&&{runtimeVersion:f.runtimeVersion,batchChecksums:f.batchChecksums,batches:f.batches?.map(b=>({manifestId:b.manifestId,registered:[...b.registered],held:[...b.held]})),registered:[...f.registered],held:[...f.held],orphanRecords:[...f.orphanRecords],recordCount:f.recordCount},records:Object.fromEntries(clean.map(id=>[id,{exists:!!e?.countries?.[id],states:core8.map(k=>e?.countries?.[id]?.fields?.[k]?.state),urls:core8.flatMap(k=>(e?.countries?.[id]?.fields?.[k]?.sources||[]).map(s=>s.locator)),ids:core8.flatMap(k=>(e?.countries?.[id]?.fields?.[k]?.evidenceIds||[])),checked:core8.map(k=>e?.countries?.[id]?.fields?.[k]?.checkedOn),refresh:e?.countries?.[id]?.fields?.safety_context?.flags?.release_refresh_required,noCostScalar:e?.countries?.[id]?.fields?.cost_context?.flags?.no_scalar_simplification,watch:core8.filter(k=>e?.countries?.[id]?.fields?.[k]?.freshness?.state==='WATCH')}]))};},{clean:CLEAN,core8:CORE8});assert.ok(state.factory,'runtime missing');assert.equal(state.factory.runtimeVersion,'atlas-country-factory-runtime-v5');assert.equal(state.factory.batchChecksums['DEX-CF5-B5'],CHECKSUM);assert.equal(state.factory.recordCount,25);assert.deepEqual([...state.factory.registered].sort(),[...PREVIOUS,...CLEAN].sort());assert.deepEqual([...state.factory.held].sort(),['ARE','LTU']);assert.deepEqual(state.factory.orphanRecords,[]);const b=state.factory.batches.find(x=>x.manifestId==='DEX-CF5-B5');assert.ok(b);assert.deepEqual([...b.registered].sort(),[...CLEAN].sort());assert.deepEqual([...b.held].sort(),['ARE','LTU']);for(const id of CLEAN){const r=state.records[id];assert.equal(r.exists,true);assert.ok(r.states.every(s=>s==='READY_FOR_PRODUCT'));assert.ok(r.urls.length>=8&&r.urls.every(u=>/^https:\/\//.test(u)));assert.ok(r.ids.length>=8);assert.ok(r.checked.every(x=>x==='2026-09-24'));assert.equal(r.refresh,true);assert.equal(r.noCostScalar,true);}assert.deepEqual(state.records.MLT.watch,['cost_context']);}
(async()=>{const browser=await chromium.launch({headless:true});for(const vp of[{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844}]){const ctx=await browser.newContext({viewport:{width:vp.width,height:vp.height}}),page=await ctx.newPage(),errs=[];page.on('pageerror',e=>errs.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&!/umami|ERR_FAILED|Failed to load resource/i.test(m.text()))errs.push('console:'+m.text())});page.on('requestfailed',r=>{if(sameOrigin(r.url()))errs.push('requestfailed:'+r.url())});page.on('response',r=>{if(sameOrigin(r.url())&&r.status()>=400)errs.push('http'+r.status()+':'+r.url())});await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.AtlasExplorer?.ready?.()&&window.ATLAS_COUNTRY_FACTORY?.recordCount===25,null,{timeout:15000});await shell(page);await verifyFactory(page);await noOverflow(page);if(vp.name==='mobile'){await page.locator('#mobileFilters').click();assert.equal(await page.locator('#mobileFilters').getAttribute('aria-expanded'),'true');}
for(const id of CLEAN){const panel=await choose(page,NAMES[id],id,`[data-atlas-country-factory-evidence][data-country="${id}"]`);assert.equal(await panel.locator('[data-evidence-field]').count(),8,`${id} evidence`);assert.ok(await panel.locator('a.detail-source').count()>=8,`${id} sources`);await disclosure(panel);await noOverflow(page);}
for(const [name,id,sel] of [['Canada','CAN','[data-atlas-canada-evidence][data-country="CAN"]'],['Portugal','PRT','[data-atlas-portugal-evidence][data-country="PRT"]'],['Allemagne','DEU','[data-atlas-germany-evidence][data-country="DEU"]'],['Royaume-Uni','GBR','[data-atlas-united-kingdom-evidence][data-country="GBR"]']]){const p=await choose(page,name,id,sel);assert.equal(await p.locator('[data-evidence-field]').count(),8,`${id} regression`);await noOverflow(page);}
await choose(page,'Géorgie','GEO','[data-atlas-country-factory-evidence][data-country="GEO"]');await page.locator('[data-save="GEO"]').click();await choose(page,'Hongrie','HUN','[data-atlas-country-factory-evidence][data-country="HUN"]');await page.locator('[data-save="HUN"]').click();assert.equal(await page.locator('#savedCount').textContent(),'2');await page.locator('#openCompare').evaluate(el=>el.click());await page.locator('#compareDialog').waitFor({state:'visible'});assert.ok(await page.locator('#compareTable [data-atlas-normalized="GEO"]').count()>=4);assert.ok(await page.locator('#compareTable [data-atlas-normalized="HUN"]').count()>=4);await page.locator('#compareDialog [data-close]').evaluate(el=>el.click());
await page.locator('[data-layer="conflict"]').evaluate(el=>el.click());await page.waitForFunction(()=>document.querySelector('[data-layer="conflict"]')?.getAttribute('aria-pressed')==='true');await choose(page,'Japon','JPN','[data-conflict-panel]');let t=await page.locator('[data-conflict-panel]').innerText();assert.match(t,/590\s*km/i);assert.match(t,/70\s*km/i);await choose(page,'Thaïlande','THA','[data-conflict-panel]');t=await page.locator('[data-conflict-panel]').innerText();assert.match(t,/Cambodge|Pattani/i);
await page.locator('[data-layer="tax"]').evaluate(el=>el.click());await page.locator('#countrySearch').fill('Chypre');await page.waitForTimeout(120);assert.equal(await page.locator('[data-country="CYP"]').count(),1);await page.locator('#countrySearch').fill('');await page.locator('[data-region="Europe"]').evaluate(el=>el.click());await page.waitForTimeout(120);assert.ok(Number((await page.locator('#resultCount').textContent()).match(/\d+/)?.[0]||0)>0);await page.locator('#resetFilters').evaluate(el=>el.click());const z0=await page.locator('#zoomValue').textContent();await page.locator('#zoomOut').evaluate(el=>el.click());await page.waitForTimeout(350);const z1=await page.locator('#zoomValue').textContent();assert.notEqual(z1,z0);await page.locator('#zoomIn').evaluate(el=>el.click());await page.waitForTimeout(350);assert.notEqual(await page.locator('#zoomValue').textContent(),z1);await noOverflow(page);await adjacent(ctx);assert.deepEqual(errs,[],'Product errors');fs.mkdirSync('qa-artifacts',{recursive:true});await page.screenshot({path:`qa-artifacts/pex-cf5-b5-${vp.name}.png`,fullPage:true});report.viewports.push({...vp,countries:CLEAN,regressions:['CAN','PRT','DEU','GBR'],conflict:['JPN','THA'],interactions:true});report.errors.push(...errs.map(e=>vp.name+':'+e));await ctx.close();}await browser.close();fs.mkdirSync('qa-artifacts',{recursive:true});fs.writeFileSync('qa-artifacts/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exit(1)});
