const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const req=p=>require(path.join(process.cwd(),p));
req('atlas-exit/country-evidence.js');req('atlas-exit/country-evidence-canada.js');
const e=globalThis.ATLAS_COUNTRY_EVIDENCE,can=e.countries.CAN;
assert.ok(can);assert.equal(can.integrationState,'published');assert.equal(e.validateCountry(can).ok,true);assert.deepEqual(Object.keys(can.fields),e.requiredFields);
const states=Object.values(can.fields).map(x=>x.state);assert.equal(states.filter(x=>x==='READY_FOR_PRODUCT').length,8);assert.equal(states.filter(x=>x==='READY_WITH_CAVEAT').length,0);
const counts={tax_residency:2,pit:1,cit_business:1,consumption_tax:1,cost_context:1,residence_visa:2,healthcare:2,safety_context:1};for(const [k,n] of Object.entries(counts))assert.equal(e.sourcesFor(can.fields[k]).length,n,k);assert.equal(Object.values(counts).reduce((a,b)=>a+b,0),11);
assert.deepEqual(e.sourcesFor(can.fields.tax_residency).map(s=>s.locator),['https://www.canada.ca/en/revenue-agency/services/tax/international-non-residents/information-been-moved/determining-your-residency-status.html','https://www.canada.ca/en/revenue-agency/services/tax/technical-information/income-tax/income-tax-folios-index/series-5-international-residency/folio-1-residency/income-tax-folio-s5-f1-c1-determining-individual-s-residence-status.html']);
assert.deepEqual(e.sourcesFor(can.fields.residence_visa).map(s=>s.locator),['https://www.canada.ca/fr/immigration-refugies-citoyennete/services/travailler-canada/eic.html','https://www.canada.ca/fr/immigration-refugies-citoyennete/services/travailler-canada/eic/admisibilite.html']);
assert.deepEqual(e.sourcesFor(can.fields.healthcare).map(s=>s.locator),['https://www.canada.ca/en/health-canada/services/health-care-system/canada-health-care-system-medicare/canada-health-act/how-publicly-funded-coverage-works.html','https://www.canada.ca/en/immigration-refugees-citizenship/services/settle-canada/health-care/universal-system.html']);
assert.equal(can.fields.tax_residency.structure.significantResidentialTiesPrimary,true);assert.equal(can.fields.tax_residency.structure.deemedResidenceDayThreshold,183);assert.equal(can.fields.tax_residency.structure.universal183DayRule,false);
assert.deepEqual(can.fields.pit.structure.federalMarginalRates,[14,20.5,26,29,33]);assert.equal(can.fields.pit.structure.provincialTerritorialOverlay,true);assert.equal(can.fields.pit.structure.allInScalarForbidden,true);
assert.equal(can.fields.cit_business.structure.federalGeneralNetRate,15);assert.equal(can.fields.cit_business.structure.qualifyingCcpcSmallBusinessRate,9);assert.equal(can.fields.cit_business.structure.provincialTerritorialOverlay,true);
assert.equal(can.fields.consumption_tax.structure.gstNonParticipatingRate,5);assert.equal(can.fields.consumption_tax.structure.hstVaries,true);assert.equal(can.fields.consumption_tax.structure.allInScalarForbidden,true);
assert.equal(can.fields.cost_context.structure.averageAnnualHouseholdSpendingCAD,76750);assert.equal(can.fields.cost_context.structure.expatBudget,false);assert.equal(can.fields.cost_context.structure.singlePersonBudget,false);
assert.equal(can.fields.residence_visa.structure.iecAvailableToFrance,true);assert.equal(can.fields.residence_visa.structure.universalRoute,false);assert.equal(can.fields.residence_visa.structure.eligibilityDetermination,false);
assert.equal(can.fields.healthcare.structure.administeredByProvincesTerritories,true);assert.equal(can.fields.healthcare.structure.automaticUniversalNewcomerCoverage,false);assert.equal(can.fields.safety_context.structure.scalarScoreForbidden,true);
for(const r of Object.values(can.fields)){assert.equal(r.verifiedOn,'2026-09-21');assert.ok(r.freshness?.trigger);assert.ok(r.sourceVintage);}
console.log('PEX-D1G Canada evidence contract PASS');
const {chromium}=require('playwright'),url='http://127.0.0.1:8000/atlas-exit/index.html';
const productHead=process.env.PRODUCT_HEAD||'';const report={productHead,baseHead:'dee08b010d9a5f25cb6d64e1d8c7dd89ae53eee4',viewports:[],errors:[]};
async function openCountry(page,name,id,panel){const dismiss=page.locator('[data-dismiss]');if(await dismiss.count())await dismiss.click().catch(()=>{});await page.locator('#countrySearch').fill(name);await page.waitForTimeout(180);const row=page.locator(`[data-country="${id}"]`).first();await row.waitFor({state:'attached'});await row.evaluate(el=>el.click());await page.waitForSelector(panel);return page.locator(panel);}
(async()=>{const browser=await chromium.launch({headless:true});for(const cfg of [{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844}]){const context=await browser.newContext({viewport:{width:cfg.width,height:cfg.height}});const page=await context.newPage();const errors=[];page.on('pageerror',err=>errors.push(String(err)));page.on('console',m=>{if(m.type()==='error'&&!/umami|ERR_FAILED|Failed to load resource|favicon/i.test(m.text()))errors.push('console: '+m.text())});await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#resultCount')?.textContent&&!/Chargement/.test(document.querySelector('#resultCount').textContent),null,{timeout:15000});await page.waitForFunction(()=>window.ATLAS_COUNTRY_EVIDENCE?.countries?.CAN?.integrationState==='published',null,{timeout:10000});assert.equal(await page.evaluate(()=>document.fonts.check('12px Manrope')),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);const z0=await page.locator('#zoomValue').textContent();await page.locator('#zoomIn').click();await page.waitForTimeout(100);const z1=await page.locator('#zoomValue').textContent();assert.notEqual(z0,z1);if(cfg.name==='mobile'){await page.locator('#mobileFilters').click();assert.equal(await page.locator('#mobileFilters').getAttribute('aria-expanded'),'true');}
const runtime=await page.evaluate(()=>{const c=window.AtlasExplorer.getCountries().find(x=>x.id==='CAN');const s=window.ATLAS_COUNTRY_EVIDENCE.countries.CAN;const commerce=window.ATLAS_COMMERCE?.countries?.CAN||{};return {tax:c.tax,taxLabel:c.taxLabel,scope:c.scope,year:c.taxYear,taxStore:window.ATLAS_TAX?.CAN?.tax,bootstrap:window.ATLAS_FISCAL_FINALIZE.countryEvidenceBootstrap,cit:commerce.cit,vat:commerce.vat,dayTest:s.fields.tax_residency.structure.deemedResidenceDayThreshold,pitRates:s.fields.pit.structure.federalMarginalRates,citRate:s.fields.cit_business.structure.federalGeneralNetRate,gst:s.fields.consumption_tax.structure.gstNonParticipatingRate};});assert.equal(runtime.tax,null);assert.equal(runtime.taxStore,null);assert.equal(runtime.taxLabel,'Fédéral + province/territoire');assert.match(runtime.scope,/fédéral.*provincial|fédéral.*territorial/i);assert.equal(runtime.bootstrap,'pex-d1g-1');assert.equal(runtime.cit,'15 % fédéral général');assert.equal(runtime.vat,'GST 5 % + HST/PST variables');assert.equal(runtime.dayTest,183);assert.deepEqual(runtime.pitRates,[14,20.5,26,29,33]);assert.equal(runtime.citRate,15);assert.equal(runtime.gst,5);
let panel=await openCountry(page,'Canada','CAN','[data-atlas-canada-evidence][data-country="CAN"]');assert.equal(await panel.locator('[data-evidence-field]').count(),8);assert.equal(await panel.locator('a.detail-source').count(),11);assert.equal(await panel.locator('[data-source-count]').count(),3);const multiCounts=await panel.locator('[data-source-count]').evaluateAll(rows=>rows.map(x=>Number(x.getAttribute('data-source-count'))));assert.deepEqual(multiCounts,[2,2,2]);const panelStates=await panel.locator('[data-evidence-state]').evaluateAll(rows=>rows.map(x=>x.getAttribute('data-evidence-state')));assert.equal(panelStates.filter(x=>x==='READY_FOR_PRODUCT').length,8);assert.equal(panelStates.filter(x=>x==='READY_WITH_CAVEAT').length,0);const text=await panel.innerText();for(const re of [/183 jours/i,/14–33 %|14.*33 %/i,/15 %/,/9 %/,/GST 5 %/,/76 750 CAD/,/EIC/i,/santé publique/i])assert.match(text,re);assert.doesNotMatch(text,/Non documenté|À documenter/i);assert.equal(await page.locator('.tax-stack').evaluate(el=>el.hidden),true);assert.equal(await page.locator('.source-disclosure').evaluate(el=>el.hidden),true);const box=await page.locator('#inspector').boundingBox();assert.ok(box&&box.x>=-1&&box.y>=-1&&box.x+box.width<=cfg.width+1&&box.y+box.height<=cfg.height+1);await page.locator('[data-save="CAN"]').click();assert.equal(await page.locator('#savedCount').textContent(),'1');
for(const [name,id,selector,sources] of [['Singapour','SGP','[data-atlas-singapore-evidence][data-country="SGP"]',10],['Suisse','CHE','[data-atlas-switzerland-evidence][data-country="CHE"]',12],['Japon','JPN','[data-atlas-japan-evidence][data-country="JPN"]',13],['Espagne','ESP','[data-atlas-spain-evidence][data-country="ESP"]',9],['Australie','AUS','[data-atlas-australia-evidence][data-country="AUS"]',11],['Thaïlande','THA','[data-atlas-evidence-panel][data-country="THA"]',8]]){panel=await openCountry(page,name,id,selector);assert.equal(await panel.locator('[data-evidence-field]').count(),8,name);assert.equal(await panel.locator('a.detail-source').count(),sources,name);}
await openCountry(page,'Canada','CAN','[data-atlas-canada-evidence][data-country="CAN"]');await page.locator('#openCompare').click();await page.locator('#compareDialog').waitFor({state:'visible'});await page.waitForTimeout(180);const compare=await page.locator('#compareTable').innerText();assert.match(compare,/Canada/);assert.match(compare,/Fédéral \+ province\/territoire/);assert.match(compare,/15 % fédéral général/);assert.match(compare,/GST\/HST\/PST|GST 5 %/);assert.ok(await page.locator('#compareTable [data-atlas-normalized="CAN"]').count()>=5);await page.locator('#compareDialog [data-close]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);fs.mkdirSync('qa-artifacts',{recursive:true});await page.screenshot({path:`qa-artifacts/pex-d1g-${cfg.name}.png`,fullPage:false});const full=await page.screenshot({path:`qa-artifacts/pex-d1g-${cfg.name}-full.png`,fullPage:true});report.viewports.push({name:cfg.name,width:cfg.width,height:cfg.height,zoom:[z0,z1],runtime,fields:8,sourceLinks:11,multiSourceGroups:multiCounts,inspector:box,fullScreenshotBytes:full.length});report.errors.push(...errors.map(x=>`${cfg.name}: ${x}`));assert.deepEqual(errors,[]);await context.close();}await browser.close();fs.writeFileSync('qa-artifacts/pex-d1g-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})().catch(err=>{console.error(err);process.exit(1)});
