const assert=require('node:assert/strict'),fs=require('node:fs');
const{chromium}=require('playwright');
const PRODUCT=process.env.ATLAS_PRODUCT_SHA||'abafbe9ec7777b65f68c39ae6fab024be25abaae';
const BASE='http://127.0.0.1:8000/atlas-exit/index.html';
const report={productSha:PRODUCT,viewports:[],errors:[]};
const sameOrigin=u=>new globalThis.URL(u).origin===new globalThis.URL(BASE).origin;
async function choose(page,name,id,selector){await page.locator('#countrySearch').fill(name);await page.waitForTimeout(170);const row=page.locator(`[data-country="${id}"]`).first();await row.waitFor({state:'attached',timeout:10000});await row.evaluate(el=>el.click());await page.waitForSelector(selector,{timeout:10000});return page.locator(selector);}
async function noOverflow(page){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'page overflow');assert.equal(await page.locator('#inspector').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true,'Inspector overflow');}
async function openEvidence(panel,{requireClosed=false}={}){assert.equal(await panel.locator('[data-evidence-field]').count(),8,'normalized evidence field count');const summary=panel.locator(':scope > summary');assert.equal(await summary.count(),1,'outer disclosure summary missing');if(requireClosed)assert.equal(await panel.getAttribute('open'),null,'fresh normalized selection should be concise by default');if((await panel.getAttribute('open'))===null)await summary.click();assert.notEqual(await panel.getAttribute('open'),null,'outer disclosure failed to open');assert.ok((await panel.locator('.atlas-evidence__row>p').evaluateAll(es=>es.map(e=>getComputedStyle(e).display))).every(v=>v==='none'),'full summaries must remain progressively disclosed');const groups=panel.locator('.atlas-evidence__source');if(await groups.count()){assert.ok((await groups.evaluateAll(es=>es.map(e=>e.hasAttribute('open')))).every(v=>v===false),'source groups should start closed');const g=groups.first();await g.locator('summary').click();assert.ok(await g.locator('a.detail-source').count()>=1,'source locator missing');assert.equal(await g.locator('a.detail-source').first().isVisible(),true,'source locator not visible after disclosure');}}
async function shell(page){for(const s of ['#countrySearch','#inspector','#openCompare','#resetFilters','#zoomIn','#zoomOut','[data-layer="tax"]','[data-layer="stability"]','[data-layer="conflict"]'])assert.equal(await page.locator(s).count(),1,`missing semantic control ${s}`);}
async function funnel(ctx){for(const[path,checks]of[['offres.html',['free-guide/usa','guide_download_click','free_funnel_cta','parcours-usa.html']],['parcours-usa.html',['atlas-events.js','USCIS','Roadmap']],['accompagnement.html',['free_funnel_cta','parcours-usa.html','offres.html?countries=USA']]]){const p=await ctx.newPage(),local=[];p.on('pageerror',e=>local.push(String(e)));p.on('requestfailed',r=>{if(sameOrigin(r.url()))local.push('requestfailed:'+r.url())});await p.goto(new globalThis.URL(path,BASE).href,{waitUntil:'domcontentloaded'});const html=await p.locator('html').innerHTML();for(const c of checks)assert.ok(html.includes(c),`${path} missing ${c}`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`${path} overflow`);assert.deepEqual(local,[],`${path} same-origin/page errors`);await p.close();}const eventJs=await(await ctx.request.get(new globalThis.URL('atlas-events.js',BASE).href)).text();assert.match(eventJs,/qualified_project/,'qualified_project event missing');const roadmapJs=await(await ctx.request.get(new globalThis.URL('parcours-usa.js',BASE).href)).text();assert.match(roadmapJs,/QEP_DEDUPE_KEY/,'QEP dedupe marker missing');const sitemap=await(await ctx.request.get(new globalThis.URL('sitemap.xml',BASE).href)).text();assert.match(sitemap,/https:\/\/atlas-expat\.fr\/parcours-usa\.html/,'D1R-17 roadmap sitemap entry missing');}
(async()=>{const browser=await chromium.launch({headless:true});for(const vp of[{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844}]){const ctx=await browser.newContext({viewport:{width:vp.width,height:vp.height}}),page=await ctx.newPage(),errs=[];page.on('pageerror',e=>errs.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&!/umami|ERR_FAILED|Failed to load resource/i.test(m.text()))errs.push('console:'+m.text())});page.on('requestfailed',r=>{if(sameOrigin(r.url()))errs.push('requestfailed:'+r.url())});page.on('response',r=>{if(sameOrigin(r.url())&&r.status()>=400)errs.push('http'+r.status()+':'+r.url())});await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.AtlasExplorer?.ready?.(),null,{timeout:15000});await shell(page);await noOverflow(page);if(vp.name==='mobile'){await page.locator('#mobileFilters').click();assert.equal(await page.locator('#mobileFilters').getAttribute('aria-expanded'),'true','mobile filters failed');}
let panel=await choose(page,'Allemagne','DEU','[data-atlas-germany-evidence][data-country="DEU"]');assert.equal(await page.evaluate(()=>window.ATLAS_COUNTRY_EVIDENCE_GERMANY?.validation?.ok===true),true,'Germany validation');assert.equal(await page.evaluate(()=>AtlasExplorer.getCountries().find(c=>c.id==='DEU')?.tax===null),true,'Germany scalar tax regression');assert.ok(await panel.locator('a.detail-source').count()>=8,'Germany locators');await openEvidence(panel,{requireClosed:true});await noOverflow(page);await page.locator('[data-save="DEU"]').click();assert.equal(await page.locator('#savedCount').textContent(),'1','Germany save');
panel=await choose(page,'Royaume-Uni','GBR','[data-atlas-united-kingdom-evidence][data-country="GBR"]');assert.equal(await panel.locator('[data-evidence-field]').count(),8,'UK evidence field count');assert.ok(await panel.locator('a.detail-source').count()>=8,'UK locators');await noOverflow(page);await page.locator('[data-save="GBR"]').click();assert.equal(await page.locator('#savedCount').textContent(),'2','UK save');
panel=await choose(page,'Canada','CAN','[data-atlas-canada-evidence][data-country="CAN"]');await openEvidence(panel,{requireClosed:false});await noOverflow(page);
await page.locator('[data-layer="conflict"]').evaluate(el=>el.click());await page.waitForFunction(()=>document.querySelector('[data-layer="conflict"]')?.getAttribute('aria-pressed')==='true');await choose(page,'Japon','JPN','[data-conflict-panel]');await page.waitForFunction(()=>/17:54/.test(document.querySelector('[data-conflict-panel]')?.textContent||''),null,{timeout:10000});let t=await page.locator('[data-conflict-panel]').innerText();assert.match(t,/590\s*km/i,'Japan 590km freshness');assert.match(t,/70\s*km/i,'Japan 70km freshness');await choose(page,'Thaïlande','THA','[data-conflict-panel]');await page.waitForFunction(()=>/Pattani|Cambodge/i.test(document.querySelector('[data-conflict-panel]')?.textContent||''),null,{timeout:10000});t=await page.locator('[data-conflict-panel]').innerText();assert.match(t,/Cambodge|Pattani/i,'Thailand bounded geography');
await page.locator('[data-layer="tax"]').evaluate(el=>el.click());await page.locator('#countrySearch').fill('Allemagne');await page.waitForTimeout(150);assert.equal(await page.locator('[data-country="DEU"]').count(),1,'search');await page.locator('#countrySearch').fill('');await page.locator('[data-region="Europe"]').evaluate(el=>el.click());await page.waitForTimeout(120);assert.ok(Number((await page.locator('#resultCount').textContent()).match(/\d+/)?.[0]||0)>0,'filter');await page.locator('#resetFilters').evaluate(el=>el.click());const z0=await page.locator('#zoomValue').textContent();await page.locator('#zoomOut').evaluate(el=>el.click());await page.waitForTimeout(350);const z1=await page.locator('#zoomValue').textContent();assert.notEqual(z1,z0,'zoom out');await page.locator('#zoomIn').evaluate(el=>el.click());await page.waitForTimeout(350);const z2=await page.locator('#zoomValue').textContent();assert.notEqual(z2,z1,'zoom in');await page.locator('#openCompare').evaluate(el=>el.click());await page.locator('#compareDialog').waitFor({state:'visible',timeout:10000});assert.ok(await page.locator('#compareTable [data-atlas-normalized="DEU"]').count()>=5,'DEU comparator normalization');assert.ok(await page.locator('#compareTable [data-atlas-normalized="GBR"]').count()>=5,'GBR comparator normalization');await page.locator('#compareDialog [data-close]').evaluate(el=>el.click());await noOverflow(page);
await funnel(ctx);assert.deepEqual(errs,[],'Product console/network/page errors');fs.mkdirSync('qa-artifacts',{recursive:true});await page.screenshot({path:`qa-artifacts/pex-qa1-${vp.name}.png`,fullPage:true});report.viewports.push({...vp,germany:true,uk:true,canadaReadability:true,japanConflict:true,thailandConflict:true,interactions:true});report.errors.push(...errs.map(e=>vp.name+':'+e));await ctx.close();}await browser.close();fs.mkdirSync('qa-artifacts',{recursive:true});fs.writeFileSync('qa-artifacts/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exit(1)});
